import { StyleSheet } from 'react-native';

export const selectBoxStyles = StyleSheet.create({
  trigger: {
    minHeight: 82,
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    elevation: 6,
  },
  triggerPressed: {
    transform: [{ scale: 0.992 }],
  },
  triggerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconWrap: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    flexShrink: 0,
    position: 'relative',
  },
  iconBadge: {
    position: 'absolute',
    right: -3,
    bottom: -4,
    minWidth: 24,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  optionIconBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    minWidth: 24,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  iconBadgeText: {
    fontSize: 9,
    lineHeight: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  textBlock: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  eyebrow: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  title: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  description: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
    flexShrink: 1,
  },
  triggerMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  triggerBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
  },
  chevronWrap: {
    width: 36,
    height: 36,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 14, 24, 0.32)',
  },
  overlayPressable: {
    flex: 1,
  },
  sheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingBottom: 18,
    maxHeight: '76%',
    elevation: 12,
  },
  sheetHandleWrap: {
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 8,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    opacity: 0.8,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingBottom: 12,
  },
  sheetHeaderTextWrap: {
    flex: 1,
    gap: 4,
  },
  sheetEyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sheetTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  closeButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  optionList: {
    gap: 10,
    paddingBottom: 6,
  },
  optionRow: {
    minHeight: 76,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  optionRowPressed: {
    transform: [{ scale: 0.992 }],
  },
  optionRowDisabled: {
    opacity: 0.52,
  },
  optionIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    flexShrink: 0,
    position: 'relative',
  },
  optionTextWrap: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  optionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  optionTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
  },
  optionBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
    overflow: 'hidden',
  },
  optionDescription: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
  },
  optionTrailing: {
    alignItems: 'flex-end',
    gap: 8,
    flexShrink: 0,
  },
  optionMeta: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  selectionMark: {
    width: 24,
    height: 24,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
